1.Write a Python Program to Add Two Matrices?

In [2]:
import numpy as np

x = np.array([[1,4,6],
        [7,5,88],
        [8,5,77]])
y = np.array([[12,43,74],
        [5,8,3],
        [8,9,9]])

z = np.add(x,y)

print(z)

[[13 47 80]
 [12 13 91]
 [16 14 86]]


2.Write a Python Program to Multiply Two Matrices?

In [3]:
import numpy as np

x = ([1, 6, 5],
           [3, 4, 8],
           [2, 12, 3])
y = ([3, 4, 6],
           [5, 6, 7],
           [6, 56, 7])

z = np.dot(x,y)
print(z)

[[ 63 320  83]
 [ 77 484 102]
 [ 84 248 117]]


3.Write a Python Program to Transpose a Matrix?

In [5]:

def Matrix(n,v=0):
    M=[]             
    for i in range(n):
        
        row =[]
        for j in range(n):
            row.append(v)
        M.append(row)
    return(M)

def crMatrix(n):
    
    M=[]             
    print("Enter the element :")
    for i in range(n):
        #stor row
        row =[]
        for j in range(n):
            row.append(int(input()))
        M.append(row)
    return(M)

def prMatrix(M,n):
    for i in range(n):
        for j in range(n):
            print(M[i][j], end=" ")
        print() 

def tpMatrix(M,n,result):
    for i in range(n):
        for j in range(n):
            result[i][j]= M[j][i]
    return result

n=int(input("Enter N for N x N matrix: "))       
M1 = crMatrix(n)
print("Display Array M1 In Matrix Form")
prMatrix(M1,n)

result = Matrix(n)
result = tpMatrix(M1,n,result)
print("Transposed Matrix")
for r in result:
    print(r)        

Enter N for N x N matrix: 3
Enter the element :
1
2
3
4
5
6
7
8
9
Display Array M1 In Matrix Form
1 2 3 
4 5 6 
7 8 9 
Transposed Matrix
[1, 4, 7]
[2, 5, 8]
[3, 6, 9]


4.Write a Python Program to Sort Words in Alphabetic Order?

In [4]:
Arr = input("Enter string")
words = Arr.split()
words.sort()
for word in words:
    print(word)

Enter string
  @media print {
    .ms-editor-squiggles-container {
      display:none !important;
    }
  }
  .ms-editor-squiggles-container {
    all: initial;
  }Ineuron is best classes
Ineuron
best
classes
is


5.Write a Python Program to Remove Punctuation From a String?

In [9]:
punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''

Arr = input("Enter a string with punctuations")


rem_punc = ""
for i in Arr:
    if i not in punctuations:
        rem_punc = rem_punc + i

# display 
print(rem_punc)

Enter a string with punctuations
  @media print {
    .ms-editor-squiggles-container {
      display:none !important;
    }
  }
  .ms-editor-squiggles-container {
    all: initial;
  }i am a mess !()-[]{};:'"\,<>./?
i am a mess 
